### ISSUE TITLE
Enhancement: Restart game with same players

### ISSUE THREAD

**Issue by joequincy** [code-words/codewords-server#43]

**Comment by joequincy** [comment]
Discussed solution:
During game over process, create new Game record and provide the generated Invite Code along with the `game-over` websocket broadcast. This would allow the UI to have an easy "play again" button that jumps players into a lobby associated with the new game.

**Comment by whois-jon-peterson** [comment]
The invite code for the new Game was added to the `game-over` message with the key `nextGame` as part of PR #49 

Documentation has been updated.
